---
name: Deploy static content to Pages
on:
  push:
    branches:
      - main
  workflow_dispatch: null
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pages repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository_owner }}/pages
          path: pages
          fetch-depth: 1
          token: ${{ secrets.PAGES_REPO_PAT }}
      - name: Get latest WASM demo
        id: latest
        env:
          GH_TOKEN: ${{ secrets.TOKEN_ORIGAMI_ARTIFACTS }}
        run: >
          RUN_ID=$(gh run list --repo origami-compiler/origami --workflow
          wasm-build.yml --status success --limit 1 --json databaseId --jq
          '.[0].databaseId')

          echo "run-id=$RUN_ID" >> "$GITHUB_OUTPUT"
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: origami-demo.zip
          repository: origami-compiler/origami
          run-id: ${{ steps.latest.outputs.run-id }}
          github-token: ${{ ssecrets.TOKEN_ORIGAMI_ARTIFACTS }}
          path: ./artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
